on:
  push:
    branches:
    - main
    - dev
    - dev/*
    - development
    - development/*
    - feature/*
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
    - '**.md'
  pull_request:
    branches:
    - main

jobs:
  test:
    strategy:
      matrix:
        version: [ '1.21' ]
        os: [ ubuntu-latest, 'windows-latest' ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.version }}
    
    - name: Download dependencies
      run: go get
    
    - name: Test
      run: go vet && go test -v ./...
  
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Create release
      run: gh release create $TAG --generate-notes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: ${{ github.ref_name }}
